### ISSUE TITLE
Supports Beanconqueror?

### ISSUE THREAD

**Issue by graphefruit** [wwong/OpenEspressoProfiler#1]
Hey there, 
I just came across this repo and read "It supports Beanconqueror" - Would love to hear more on this!
Best
Lars

**Comment by wwong** [comment]
Hey Lars,

Big fan of your app. This project implements the same BLE services as the the Pressensor, but using some cheap off-the-shelf parts. When I open up Beanconqueror, it recognizes the device as a PRS without needing any modification to the app.


Wilson

**Comment by graphefruit** [comment]
Hey @wwong,
thanks for your response!
Great to hear!
I'm happy to get a quick note from you when all is set up, so I can reference this project as a DIY solution inside of Beanconqueror and in the FAQ :)
Have a great cup of coffee
Lars
