### ISSUE TITLE
need support

### ISSUE THREAD

**Issue by winner69** [wwong/OpenEspressoProfiler#4]
1. Can I use a 0.5-4.5V max 25bar sensor? If so, do I have to modify the code? Please give me some advice.
2. how to calibrate to get the most accurate value (in application) ? What should I do? Please advise.
3. Does it support showing battery percentage in the app?
thank you

**Comment by wwong** [comment]
> 1. Can I use a 0.5-4.5V max 25bar sensor? If so, do I have to modify the code? Please give me some advice.

It could work, but you might sacrifice some precision (hopefully not enough to matter?). I only have a 200PSI (~14 bar) sensor here, so you'll need to tinker with the code and voltage divider values to see what works best for your setup.

To start, you can try changing this line to match your sensor (25 bar is roughly 363psi):

https://github.com/wwong/OpenEspressoProfiler/blob/c7540bde0ad15e634fd81b53951a14ee17156320/src/config.h#L10

> 2. how to calibrate to get the most accurate value (in application) ? What should I do? Please advise.

I didn't write any code for calibrating in-app. I found that the values don't exactly match my manual pressure gauge, but is pretty close.

If the current algorithm isn't accurate enough or you want to try calibrating by hand, the initial commit (before I added config.h) used values that were manually calculated with a linear regression. You can run through the same process by reading off the ADC readings while holding pressure steady at 1/2/3/etc bar and fitting a line. The code should have [two lines](https://github.com/wwong/OpenEspressoProfiler/blob/d822d0030c80832bd329add07ad236c2f5c55228/src/main.cpp#L15-L16) where you can plug in the m and b values for y=mx+b gleaned from running the regression.

> 3. Does it support showing battery percentage in the app?

I didn't write code to calculate battery percentage. I have my ESP32 plugged into a wall charger, so the battery code is hardcoded to report 100%


If you find the time to improve any of the code or add new functionality, PRs are welcome. Thanks for taking a look!

**Comment by winner69** [comment]
Thank you.
